### ISSUE TITLE
MSC Axis values lost when saving / reloading getMSC cube

### ISSUE THREAD

**Issue by noralinscheid** [JuliaDataCubes/ESDL.jl#265]
I would like to apply the `getMSC` function to a cube, save the resulting cube (with "MSC" axis) and later reload it from disk. When I try this routine, the "MSC" axis values lose their `DateTime` format and are loaded as Float range instead of the original Date range.
I guess the issue might also lie in `YAXArrays` (`savecube`/`open_dataset`?), but it only occurs with the MSC cube as far as I saw.

Renaming the axis to "Time" fixes the issue. 

Is there an extra routine for Time/Date axes somewhere that should also apply for "MSC" (or rather, apply by axis eltype and not axis name) -> YaxArrays `toaxis`?  I checked that this behaviour is not a problem of the axis type directly but only axis name (MSC axis is type `StepRange{DateTime, Day}`, usual axis type is `Vector{DateTime}` but changing the axis type accordingly did not change the save/reload behaviour).

Any ideas?

```
cube = esdc()
ctest = cube[lon=(10,11),lat=(50,51),var="air_temperature_2m"]

cmsc = getMSC(ctest)
savecube(cmsc, "testmsc")
creloaded = Cube("testmsc") # returns wrong axis values


cswap = renameaxis!(cmsc, "MSC" => "Time")
savecube(cswap, "testmsc2")
creloaded2 = Cube("testmsc2") # returns correct axis values
```

**Comment by meggart** [comment]
Hi Nora, I made a quick fix and it will be available as soon as https://github.com/meggart/YAXArrays.jl/pull/88 is merged. I hope to finish this by tomorrow.
