### ISSUE TITLE
Links to docs is broken

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaDataCubes/ESDL.jl#270]
Looks like there is an issue with the document generation. 

See: http://esa-esdl.github.io/ESDL.jl/

**Comment by MartinuzziFrancesco** [comment]
Sorry about that, we migrated the repository so there are a couple of broken links around. I should be able to fix them this week

**Comment by MartinuzziFrancesco** [comment]
The link to the docs in the readme is now working thanks to #272 

https://juliadatacubes.github.io/ESDL.jl/latest/
